/* PicoTCP - Definition file - DO NOT EDIT */
/* This file is automatically generated at compile time */
#ifndef PICO_DEFINES_H
#define PICO_DEFINES_H

#define PICO_SUPPORT_ETH
#define PICO_SUPPORT_IPV4
#define PICO_SUPPORT_TCP
#endif
